name: SCSV CI
on: push

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run Tests
      run: |
        bin/ensure-poetry
        bin/poetry install
        bin/poetry run black --check --diff scsv tests
        bin/poetry run isort --check --diff scsv tests
        bin/poetry run flake8 --extend-ignore=E501 scsv tests
        bin/poetry run pytest
        bin/poetry run mypy scsv
